pre-commit:
  parallel: false
  skip:
    - merge
    - rebase
  commands:
    lint-code:
      glob: "*.php"
      run: php vendor/bin/parallel-lint {staged_files}
  
    lint-code-psr12:
      glob: "*.php"
      run: php vendor/bin/phpcs --standard=PSR12 {staged_files}

pre-push:
  parallel: true
  commands:
    analyse-code:
      glob: "*.{php,neon}"
      run: php vendor/bin/phpstan analyse --configuration=config/phpstan.neon --memory-limit=1G

    test-code:
      glob: "*.{php,xml,neon}"
      run: XDEBUG_MODE=off php vendor/bin/phpunit --configuration config/phpunit.xml --colors=always
