name: PHPBench Benchmark

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: phpbench
          extensions: opcache
          coverage: none
          ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M
    
      - name: Install Composer Dependencies
        run: composer install

      - name: Run PHPBench
        run: vendor/bin/phpbench run --report=aggregate

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v3
        with:
          name: phpbench-results
          path: build/benchmark/aggregate
